### PR TITLE
Webpack fix for new game version

### LINKED ISSUE #17: Extension no longer works
Earlier today, the extension worked beautifully, but I revisited the game about 2-3 hours later and it no longer works. It is just the normal game, even though the surviv.io logo is still changed. Any ways to fix?

### PR DESCRIPTION
**Pull request by zimm1**
Fixes #17 #18 #19 #20

### CODE REVIEW

**Comment by Kalaborative** [comment]
Could you revise your PR to include movement with arrow keys? Currently you can only move around with WASD.

**Comment by Koksupl1234** [comment]
how to turn it on ?

**Comment by Koksupl1234** [comment]
How tu use this ?

**Comment by Kalaborative** [comment]
@Koksupl1234 use his fork, download as ZIP, extract the folder and go to Chrome extensions and click load unpacked.

**Comment by reuke** [comment]
Just got back from vacation.
Thank you, @Zimm1 for your contribution! Will check it ASAP.

**Comment by reuke** [comment]
Oh, so they just changed the way of ID's generation for webpack modules.

**Comment by zimm1** [comment]
Yeah, I suspected that from the webpack loading error in chrome console, that was an easy fix. Nice work with this cheat tho :)

**Pull request merged**
